/***************************************************************************
 *
 *
 * groupingDB.c
 *
 * Created by Belkin International, Software Engineering on XX/XX/XX.
 * Copyright (c) 2012-2013 Belkin International, Inc. and/or its affiliates. All rights reserved.
 *
 * Belkin International, Inc. retains all right, title and interest (including all
 * intellectual property rights) in and to this computer program, which is
 * protected by applicable intellectual property laws.  Unless you have obtained
 * a separate written license from Belkin International, Inc., you are not authorized
 * to utilize all or a part of this computer program for any purpose (including
 * reproduction, distribution, modification, and compilation into object code)
 * and you must immediately destroy or return to Belkin International, Inc
 * all copies of this computer program.  If you are licensed by Belkin International, Inc., your
 * rights to utilize this computer program are limited by the terms of that license.
 *
 * To obtain a license, please contact Belkin International, Inc.
 *
 * This computer program contains trade secrets owned by Belkin International, Inc.
 * and, unless unauthorized by Belkin International, Inc. in writing, you agree to
 * maintain the confidentiality of this computer program and related information
 * and to not disclose this computer program and related information to any
 * other person or entity.
 *
 * THIS COMPUTER PROGRAM IS PROVIDED AS IS WITHOUT ANY WARRANTIES, AND BELKIN INTERNATIONAL, INC.
 * EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OF
 * MERCHANTIBILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
 *
 *
 ***************************************************************************/
#include <stdio.h>
#include <unistd.h>
#include <syslog.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>
#include <malloc.h>
#include <pthread.h>
#include <sys/stat.h>

#include "types.h"
#include "defines.h"
#include "logger.h"

#include "WemoDB.h"

#include "utlist.h"

#include "groupingDS.h"
#include "groupingExtIf.h"
#include "groupingDefs.h"

//Grouping DB handle
sqlite3 *g_GroupingDB=NULL;

/*
	 4.1.1		End Devices Schema Table
	 This table will have the following elements along with their association with a group identifier:
	 1.	EndDeviceIdx . This corresponds to the index assigned to end devices while joining with the bridge
	 and will be unique corresponding to each joined end devices.
	 2.	DeviceID . This is the unique identifier such as MAC of each end devices.
	 3.	DeviceStatus . This status will indicate whether the end devices are currently paired with bridge or not.
	 4.	IconName . This is name of the icon representing the end device.
	 5.	IconVersion . This indicates the version of the icon corresponding to the end devices.
	 6.	DeviceCapability . This element will have the capability id along with current value supported by the
	 end device under this group. If the device supports more than one capability then data will be stored
	 using the following format:
	 <CapabilityId1:CurrentValue1, CapabilityId2:CurrentValue2>
	 7.	GroupID . This id will be generated by Smart App when user creates a group. This id will be set to 0 if
	 end device is not a part of any group.

	 This DB schema will be created at the initialization of the core modules on WeMo Bridge device. 
	 Entries corresponding to end devices will be entered to this table as when end device starts
	 joining WeMo Bridge device network. The elements .IconName. and .IconVersion. will be populated
	 with default values when end devices joins WeMo Bridge network first time and can be modified by
	 user from Smart App thereafter.
	 The element .DeviceCapability. will also be populated when the end devices join and publish their 
	 capabilities. This module will interact with capability module to learn the end devices capability.
	 By default when an entry gets created first time for an end device to this schema table the .GroupId.
	 value will be set to 0 and will be populated to Smart App generated .GroupId. when this end device
	 is added to a group.
 */
int createDevciesSchemaTable(sqlite3 *grpDB)
{
		int retStatus = PLUGIN_FAILURE;

		//Devices Schema table for storing end devices details
		TableDetails DevicesSchemaTable[MAX_DEVICES_SCHEMA_COLUMN]=
		{{"EndDeviceIdx","int"},{"DeviceID","int"},{"DeviceStatus","int"},{"IconName","char"},{"IconVersion","char"},{"DeviceCapability","char"},{"GroupId","int"},{"TimeStamp","long"}};

		//create all Grouping tables
		if(WeMoDBCreateTable(&grpDB, "DevicesSchemaTable", DevicesSchemaTable, 0, MAX_DEVICES_SCHEMA_COLUMN)) {
				retStatus = PLUGIN_FAILURE;
				APP_LOG("GROUPING", LOG_DEBUG, "GroupingsSchemaTable Creation Failed!");
				goto func_exit;
		} else {
				retStatus = PLUGIN_SUCCESS;
				APP_LOG("GROUPING", LOG_DEBUG, "DevicesSchemaTable Created Successfully!");
				goto func_exit;
		}

func_exit:
		return retStatus;
}

/*
	 4.1.2		Group Schema Table
	 1.	GroupID . This id will be generated by Smart App when user creates a group.
	 2.	GroupCapability . This element corresponds to the overall group capability to which this 
	 end device belongs to. Format to store this information will be same as stated in .DeviceCapability..
	 3.	NumberOfCapabilities . This element will indicate the number of .,. separated capability id
	 and current value pair under the .GroupCapability. element.
	 4.	GroupIconName . This is name of the icon representing the group to which end device belongs to.
	 5.	GroupIconVersion - This indicates the version of the icon corresponding to the group to which
	 end device belongs to.

	 If no group is created from Smart App then this schema table will not have any entry.
	 Whenever any group is created by Smart App, it must also provide the .Group Capability.. 
	 The other two elements .GroupIconName. and .GroupIconVersion. will be set to default values
	 until edited by Smart App.
 */
int createGroupingsSchemaTable(sqlite3 *grpDB)
{
		int retStatus = PLUGIN_FAILURE;

		//Devices Schema table for storing end devices details
		TableDetails GroupingsSchemaTable[MAX_DEVICES_SCHEMA_COLUMN]=
		{{"GroupId","int"},{"GroupCapability","char"},{"NumberOfCapabilities","int"},{"GroupIconName","char"},{"GroupIconVersion","char"},{"TimeStamp","long"}};

		//create all Inisght tables
		if(WeMoDBCreateTable(&grpDB, "GroupingsSchemaTable", GroupingsSchemaTable, 0, MAX_GROUPINGS_SCHEMA_COLUMN)) {
				retStatus = PLUGIN_FAILURE;
				APP_LOG("GROUPING", LOG_DEBUG, "GroupingsSchemaTable Creation Failed!");
				goto func_exit;
		} else {
				retStatus = PLUGIN_SUCCESS;
				APP_LOG("GROUPING", LOG_DEBUG, "GroupingsSchemaTable Created Successfully!");
				goto func_exit;
		}

func_exit:
		return retStatus;
}

int initGroupingDB(char *dbName)
{
		int retStatus = PLUGIN_FAILURE;
		struct stat FileInfo;

		//check if grouping DB file already exists
		if(stat(dbName, &FileInfo) != -1) {
				APP_LOG("GROUPING", LOG_DEBUG, "Grouping DB already Exists!");
				//open gouping DB and get the handle 
				if(InitDB(dbName,&g_GroupingDB)) {
						retStatus = PLUGIN_FAILURE;
						goto func_exit;
				} else {
						retStatus = PLUGIN_SUCCESS;
						APP_LOG("GROUPING", LOG_DEBUG, "Grouping DB Init done!");
				}
		} else {
				//init grouping DB
				if(!InitDB(dbName,&g_GroupingDB)) {
						//create DevicesSchemaTable table
						retStatus = createDevciesSchemaTable(g_GroupingDB);
						if (retStatus < PLUGIN_SUCCESS) {
								goto func_exit;
						}
						//create GroupingSchemaTable table
						retStatus = createGroupingsSchemaTable(g_GroupingDB);
						if (retStatus < PLUGIN_SUCCESS) {
								goto func_exit;
						}

						APP_LOG("GROUPING", LOG_DEBUG, "grouping DB created and tables added successfully!");
				} else {
						goto func_exit;
				}
		}

func_exit:
		APP_LOG("GROUPING", LOG_DEBUG, "Grouping DB initialization returned %d", retStatus);
		return retStatus;
}
